### ISSUE TITLE
Add a How to register section

### ISSUE THREAD

**Issue by IbraheemHaseeb7** [rascui/raswars#5]
You can add random text in the sections. Follow the design shown below. 

![image](https://github.com/rascui/raswars/assets/81369271/e98312ce-be56-4a9d-a853-2228a90ea8cd)

The line on the left you see should be similar to the line you can see in the center of this design

![image](https://github.com/rascui/raswars/assets/81369271/3e99e807-fa91-41a3-a9a7-45af58e15ce6)

**Comment by evnxprk** [comment]
So is this just adding a section of text showing how to register?

**Comment by evnxprk** [comment]
If possible, could you provide more information on the registration?

**Comment by IbraheemHaseeb7** [comment]
Hello @evnxprk,

Thanks for reaching out before working on the issue. What we  need is to simply display the text as it is right now. We can put lorem ipsum about 25 length of 3 sections for now and at the end a non-functioning register button.

Later we can add functionality to the button and also the actual rules and regulations for this competition.

**Comment by evnxprk** [comment]
Okay, I would be interested in trying my take on this issue.

**Comment by IbraheemHaseeb7** [comment]
@evnxprk perhaps you can look at another issue as this one is already addressed? You can work on issue for footer. We basically need to change our current footer to this design below:

![image](https://github.com/rascui/raswars/assets/81369271/eaba5e49-ea38-4ff5-8fec-17de83564a07)

**Comment by evnxprk** [comment]
Okay I am interested in doing the footer. What tech stacks are you using in this project?
